### ISSUE TITLE
Invalid Queue Names

### ISSUE THREAD

**Issue by sbosell** [ServiceStack/ServiceStack.Azure#11]
I'm not sure if there was a relatively recent change but Azure SB is rejecting the default names with a colon.  A workaround is:

`QueueNames.MqPrefix = "mq-";`

Need to probably update the library and/or run through the tests to ensure they are passing.

**Comment by mythz** [comment]
Should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Azure/commit/827543850e930292d7e44ba82ae7de326a5f7b9e). This change is available from v5.1.1 that's now [available on MyGet](http://docs.servicestack.net/myget).
