### ISSUE TITLE
Project is not compiling

### ISSUE THREAD

**Issue by laitang2000** [ServiceStack/ServiceStack.Azure#14]
QueueClientExtensions.FromMessageBody(this Stream messageBody)

The ReadToEnd is missing a lib.

**Comment by mythz** [comment]
I've just checked in the latest .dlls in [this commit](https://github.com/ServiceStack/ServiceStack.Azure/commit/327bcea881f01549f7fb782d3714906ca6ad931d).

If you just want to access the latest pre-release version of ServiceStack.Azure you can [install the MyGet packages](http://docs.servicestack.net/myget) which contains the latest version of each project.

**Comment by laitang2000** [comment]
Still not working, the myget feed still reports Sunday as the last published date.

As Running the source with some added project that is targeting 4.71 and reports the error

{"Method not found: 'System.String ServiceStack.StreamExtensions.ReadToEnd(System.IO.Stream)'."} | System.Exception {System.MissingMethodException}
