### ISSUE TITLE
Azure Storage Folders

### ISSUE THREAD

**Issue by sbosell** [ServiceStack/ServiceStack.Azure#5]
I'm happy to see this project get some TLC lately.   One of the limitations of azure blob storage is there are no "folders" in the classical sense.  I checked the source code and didn't see a way to  create a folder (either using some convention or otherwise).    The specific use case is common to provide a way for users to browse the files that are stored, create folders to store them/etc.  

Is this something that is planned?

**Comment by xplicit** [comment]
You can look at this test case to see how to create files inside folders and work with folder.

https://github.com/ServiceStack/ServiceStack.Azure/blob/master/tests/ServiceStack.Azure.Tests/Storage/AzureBlobVirtualPathProviderTests.cs#L225

For example, this sting creates files in subfolders:

https://github.com/ServiceStack/ServiceStack.Azure/blob/master/tests/ServiceStack.Azure.Tests/Storage/AzureBlobVirtualPathProviderTests.cs#L241
