### ISSUE TITLE
Cache Rowkey Restrictions

### ISSUE THREAD

**Issue by sbosell** [ServiceStack/ServiceStack.Azure#6]
The cache provider let's you set whatever string value to the id however the underlying storage has restrictions. I think they should be stripped out.

The following characters are not allowed in PartitionKey and RowKey fields:

The forward slash (/) character
The backslash (\) character
The number sign (#) character
The question mark (?) character

**Comment by mythz** [comment]
Where not in the habit of duplicating server errors on the client, if the underlying storage has these restrictions the App should not be using them. Stripping them out can lead to unexpected collisions.

**Comment by sbosell** [comment]
Fair enough. I might suggest an update to the docs.
