### ISSUE TITLE
Should the Get<T> Complete the Service Bus Message

### ISSUE THREAD

**Issue by sbosell** [ServiceStack/ServiceStack.Azure#7]
It was my understanding from the docs an explicit Ack was required to complete the processing of the message but it seems that that Get<T> calls Complete which means it will remove it from the queue.

The docs state:

> Also shown in this example is an explicit Ack (which should be done for each message you receive) to tell the MQ Broker that you’ve taken responsibility of the message so it can safely remove it off the queue.

But the code for Get<T> calls complete removing it from the queue:
      if (msg != null)
                sbClient.CompleteAsync(msg.SystemProperties.LockToken).Wait();

Can you clarify this and/or update it to be consistent with the docs?

**Comment by onlyann** [comment]
Without an explicit Ack, some messaging scenarios cannot be supported.

Would it be possible to move `CompleteAsync` in the `Ack` of the client instead ?

I did something like that in [my attempt to provide an Azure MQ Server option](https://github.com/onlyann/ServiceStack.AzureServiceBus).

**Comment by xplicit** [comment]
AutoComplete was replaced with exlicity Ack in https://github.com/ServiceStack/ServiceStack.Azure/commit/1652933a122fa6e7468c82271fd55f8a2ed9b2fe commit

This change is available on [MyGet](https://docs.servicestack.net/myget) since v4.5.15

Regardling docs some of MQ providers (for example RedisMessageQueueClient) does not have `Ack` implemented and messages are removed from queue immediately on receive.

**Comment by sbosell** [comment]
@xplicit I'm getting some strange behaviour (.net core) where a message is published to a handler that returns null and it will infinitely process the same message.  Do I need to manually do something in the handler to complete it?  My original question here was about manually calling get as I needed to process the dlq but I'm not sure now if the handler calls it or the developer?

**Comment by xplicit** [comment]
@sbosell When you process the message by the handler and return null it goes to `.outq`and you do not need to call `Ack` for completion, it's called by the message handler. Message goes to `.dlq` only if exception occurred during processing. What are you going to accomplish? And do you have the same bahaviour on .NET?

**Comment by sbosell** [comment]
Project is core but it is definitely stuck in a loop as I published one message and it keeps processing it over and over. 
Tomorrow I'll test in.net to see if it is the same. 
		
		

		Sam
	




On Tue, Sep 19, 2017 at 11:01 PM -0500, "Sergey Zhukov" <notifications@github.com> wrote:












@sbosell When you process the message by the handler and return null it goes to .outqand you do not need to call Ack for completion, it's called by the message handler. Message goes to .dlq only if exception occurred during processing. What are you going to accomplish? And do you have the same bahaviour on .NET?

**Comment by sbosell** [comment]
@xplicit confirmed the issue in .net too.  You can find a test project here.  https://www.dropbox.com/s/riegicvk16ug6y4/ServiceBusTest.zip?dl=0

It simulates what I'm doing.  I have a webhook from jira posting to my service.  The service publishes the message.  The handler processes it and returns.  The handler will fire "infinitely" or until it gets dead lettered in service bus which to me indicates the handler isn't completing it.  

The same code with redis (in my original project) works as expected.  After the handler returns the message is completed.

**Comment by xplicit** [comment]
@sbosell I made changes in messages handling and completion in the commit https://github.com/ServiceStack/ServiceStack.Azure/commit/e153873b41e55067464d20a5d61ff0a11ae47e00 and after this change your solution seems to work as expected. This change is available on MyGet in v4.5.15, you might need to clear nuget cache using command `dotnet nuget locals all -c` before update nuget packages.

Can you try and confirm if the latest version works for you or you still encounter an errors?

**Comment by onlyann** [comment]
I was just about to describe this undocumented behaviour where a locked token can only be used with the same client instance. Nice one.

**Comment by xplicit** [comment]
@onlyann yeah, that's strange that only the same client can control locktoken but now the issue when different clients on the same queue tried to unlock the message should be resolved.

**Comment by sbosell** [comment]
@xplicit The handler now seems to be completing the message correctly.  At least it isn't in a loop until dlq'd anymore.  I'll test it some more and let you know if I see any ohter issues.  Thank you for addressing it so quickly.
