### ISSUE TITLE
Missing Append Blob

### ISSUE THREAD

**Issue by sbosell** [ServiceStack/ServiceStack.Azure#8]
I was testing the request logger with the azure vfs and the log writes are failing.  I checked and the appendfile is not implemented which requires an append blob.  I was going to create a pull request to add it but do you prefer a separate provider or if/then's checks on the existing one that implements append/write where applicable?

After reviewing I'm thinking a dedicated AzureAppendBlobVirtualFiles might be best otherwise it requires too much checking to see if a blob is an append blob and converting it/etc when I think the common use case is logging which just requires appending.

**Comment by xplicit** [comment]
Yeah, it would be better to create new type `AzureAppendBlobVirtualFiles` because blob types cannot be converted to each other and every blob type has unique features which are not working in other blob types.

**Comment by sbosell** [comment]
I think the biggest difference is I believe the appendblob's only support async methods.  I'll create a separate AzureAppendBlobVirtualFile(s) per your suggestion.

**Comment by sbosell** [comment]
@xplicit I can't get nUnit to run in VS 2017.   Any suggestions?  I'm testing it in the CsvRequestLogger and some services to pull them but I'd prefer to run the nUnit tests.

**Comment by mythz** [comment]
We use ReSharper to run NUnit tests in VS2017, otherwise Rider lets you run NUnit tests as well.

**Comment by sbosell** [comment]
Thanks.  It works now.  The emulator doesn't support append blobs so I'm testing against Azure Hosted Storage and I noticed that the AzureBlobVirtualPathProviderTests pass when run against the emulator and fail otherwise due to the setup and teardowns.  I'll try to address this in the append tests.
